import { ReactNode } from 'react';

import AnalyticsWrapper from './components/AnalyticsWrapper';

interface Props {
  children: ReactNode;
}

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

function RootLayout({ children }: Props) {
  return (
    <html lang="ko">
      <body>
        {children}
        <AnalyticsWrapper />
      </body>
    </html>
  );
}

export default RootLayout;
