import '@/styles/global.css';

import { Analytics } from '@vercel/analytics/react';
import { ReactNode } from 'react';

import { firaMono } from '@/styles/font';

interface Props {
  children: ReactNode;
}

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

function RootLayout({ children }: Props) {
  return (
    <html
      className={`${firaMono.variable} overscroll-none`}
      lang="ko"
    >
      <body className="flex min-h-screen flex-col items-center overscroll-none bg-background font-monospace text-stone-200 selection:bg-lime-900 selection:text-stone-50">
        {children}
        <Analytics />
      </body>
    </html>
  );
}

export default RootLayout;
