import '@/styles/index.scss';

import { Analytics } from '@vercel/analytics/react';
import { ReactNode } from 'react';

import StyledComponentsProvider from '@/app/components/StyledComponentsProvider';

interface Props {
  children: ReactNode;
}

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

function RootLayout({ children }: Props) {
  return (
    <html lang="ko">
      <body>
        <StyledComponentsProvider>{children}</StyledComponentsProvider>
        <Analytics />
      </body>
    </html>
  );
}

export default RootLayout;
