import ClientComponent from '@/app/components/ClientComponent';

import styles from './page.module.scss';

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

function Index() {
  return (
    <>
      <header className={styles.header}>next.js boilerplate</header>
      <main className="container">
        <h1>Next.js Boilerplate</h1>
        <ClientComponent />
        <ul>
          <li>Next.js</li>
          <li>Typescript</li>
        </ul>
      </main>
    </>
  );
}

export default Index;
